In [3]:
import pandas as pd
import numpy as np

In [4]:
obj_array = np.random.normal(20, 2.5, 40).reshape(8, 5)
obj_lista = list(obj_array[0])
obj_lista

[16.43272491244383,
 15.53514574539565,
 18.289909729264618,
 20.465661130012453,
 20.91109449579367]

In [8]:
conta = 0
for valor in obj_lista:
    print(f"{conta} - {valor}")
    conta += 1

0 - 16.43272491244383
1 - 15.53514574539565
2 - 18.289909729264618
3 - 20.465661130012453
4 - 20.91109449579367


In [7]:
for index, valor in enumerate(obj_lista):
    print(f"{index} - {valor}")

0 - 16.43272491244383
1 - 15.53514574539565
2 - 18.289909729264618
3 - 20.465661130012453
4 - 20.91109449579367


In [9]:
conta = 0
while conta < len(obj_lista):
    print(f"{conta} - {obj_lista[conta]}")
    conta += 1

0 - 16.43272491244383
1 - 15.53514574539565
2 - 18.289909729264618
3 - 20.465661130012453
4 - 20.91109449579367


In [12]:
for num in range(len(obj_lista)):
    print(f"{num} - {obj_lista[num]}")

0 - 16.43272491244383
1 - 15.53514574539565
2 - 18.289909729264618
3 - 20.465661130012453
4 - 20.91109449579367


In [14]:
for valor in enumerate(obj_lista):
    for num in range(len(valor)):
        print(f"{valor[num]}")

0
16.43272491244383
1
15.53514574539565
2
18.289909729264618
3
20.465661130012453
4
20.91109449579367


In [15]:
obj_disc = {
    '0': 10,
    '1': 20,
    '2': 30,
    '3': 40,
    '4': 50
}
obj_disc

{'0': 10, '1': 20, '2': 30, '3': 40, '4': 50}

In [20]:
for index in obj_disc.keys():
    print(f"{index} - {obj_disc[index]}")

0 - 10
1 - 20
2 - 30
3 - 40
4 - 50


In [22]:
for valores in obj_disc.items():
    print(f"{valores[0]} - {valores[1]}")

0 - 10
1 - 20
2 - 30
3 - 40
4 - 50


In [23]:
for valor in obj_disc.values():
    print(f"{valor}")

10
20
30
40
50


In [27]:
for linha in obj_array:
    print(f"{linha[:3]}")

[16.43272491 15.53514575 18.28990973]
[19.84922935 19.24950491 18.5770441 ]
[18.36233341 19.0063781  20.01712639]
[21.2388529  20.24760897 18.40146992]
[17.61864578 23.01041769 24.67700842]
[21.20055622 19.66222895 18.43827167]
[17.48807306 19.08162049 24.86556731]
[20.54146235 18.25037044 22.42744598]


In [28]:
for linha in obj_array[3]:
    print(f"{linha}")

21.238852904375438
20.24760897122839
18.401469919946248
19.834408508225113
20.041844823329026


In [29]:
for valor in enumerate(obj_array[3]):
    print(f"{valor}")

(0, 21.238852904375438)
(1, 20.24760897122839)
(2, 18.401469919946248)
(3, 19.834408508225113)
(4, 20.041844823329026)


In [30]:
obj_data = pd.DataFrame(obj_array)
obj_data

,0,1,2,3,4
0,16.432725,15.535146,18.289910,20.465661,20.911094
1,19.849229,19.249505,18.577044,16.360870,22.539132
2,18.362333,19.006378,20.017126,17.558502,17.617880
3,21.238853,20.247609,18.401470,19.834409,20.041845
4,17.618646,23.010418,24.677008,18.787412,20.379545
5,21.200556,19.662229,18.438272,18.581975,20.492268
6,17.488073,19.081620,24.865567,18.371960,21.381736
7,20.541462,18.250370,22.427446,23.345367,19.921395


In [32]:
for valor in obj_data:
    print(f"{obj_data[valor]}")

0    16.432725
1    19.849229
2    18.362333
3    21.238853
4    17.618646
5    21.200556
6    17.488073
7    20.541462
Name: 0, dtype: float64
0    15.535146
1    19.249505
2    19.006378
3    20.247609
4    23.010418
5    19.662229
6    19.081620
7    18.250370
Name: 1, dtype: float64
0    18.289910
1    18.577044
2    20.017126
3    18.401470
4    24.677008
5    18.438272
6    24.865567
7    22.427446
Name: 2, dtype: float64
0    20.465661
1    16.360870
2    17.558502
3    19.834409
4    18.787412
5    18.581975
6    18.371960
7    23.345367
Name: 3, dtype: float64
0    20.911094
1    22.539132
2    17.617880
3    20.041845
4    20.379545
5    20.492268
6    21.381736
7    19.921395
Name: 4, dtype: float64


In [40]:
for index in obj_data.index:
    if index > 3:
        print(f"{obj_data.iloc[index]}")

0    17.618646
1    23.010418
2    24.677008
3    18.787412
4    20.379545
Name: 4, dtype: float64
0    21.200556
1    19.662229
2    18.438272
3    18.581975
4    20.492268
Name: 5, dtype: float64
0    17.488073
1    19.081620
2    24.865567
3    18.371960
4    21.381736
Name: 6, dtype: float64
0    20.541462
1    18.250370
2    22.427446
3    23.345367
4    19.921395
Name: 7, dtype: float64


In [45]:
for col in obj_data.columns:
    print(f"{obj_data[col]}")

0    16.432725
1    19.849229
2    18.362333
3    21.238853
4    17.618646
5    21.200556
6    17.488073
7    20.541462
Name: 0, dtype: float64
0    15.535146
1    19.249505
2    19.006378
3    20.247609
4    23.010418
5    19.662229
6    19.081620
7    18.250370
Name: 1, dtype: float64
0    18.289910
1    18.577044
2    20.017126
3    18.401470
4    24.677008
5    18.438272
6    24.865567
7    22.427446
Name: 2, dtype: float64
0    20.465661
1    16.360870
2    17.558502
3    19.834409
4    18.787412
5    18.581975
6    18.371960
7    23.345367
Name: 3, dtype: float64
0    20.911094
1    22.539132
2    17.617880
3    20.041845
4    20.379545
5    20.492268
6    21.381736
7    19.921395
Name: 4, dtype: float64
