In [2]:
num_1 = 5
num_2 = 10
print(num_1 + num_2)
print(num_1 - num_2)

15
-5


In [7]:
tupla = (1, 2, 3)
tupla_2 = (1, 2, 20)

print(tupla + tupla_2)

(1, 2, 3, 1, 2, 20)


In [8]:
tupla += tupla_2
display(tupla)
display(tupla_2)

(1, 2, 3, 1, 2, 20)

(1, 2, 20)

In [15]:
lista_da_tupla = list(tupla)
display(lista_da_tupla)

[1, 2, 3, 1, 2, 20]

In [ ]:
lista_da_tupla[2] += 2 # se eu rodar varias vezes, o valor do índice 2 vai aumentando
lista_da_tupla

[1, 2, 5, 1, 2, 20]

In [26]:
dicionário = {'a': 1, 'b': 14, 'c': 3}
dicionário2 = {'a': 1, 'b': 2, 'c': 20}
print(dicionário, dicionário2)

{'a': 1, 'b': 14, 'c': 3} {'a': 1, 'b': 2, 'c': 20}


In [25]:
dicionário.update(dicionário2)
dicionário

{'a': 1, 'b': 2, 'c': 20}

In [27]:
import numpy as np
import pandas as pd

In [33]:
array = np.array(lista_da_tupla)
array

array([ 1,  2,  5,  1,  2, 20])

In [34]:
array += 2
array

array([ 3,  4,  7,  3,  4, 22])

In [ ]:
len

In [ ]:
array *= array #se eu rodar varias vezes, o valor do array vai aumentando exponencialmente
array

array([  9,  16,  49,   9,  16, 484])

In [40]:
np.insert(arr=array, obj=2, values=100) # equivale a mesma coisa para a indexaçao de lista
# lista_da_tupla[2] = 100

array([  9,  16, 100,  49,   9,  16, 484])

In [43]:
np.insert(arr=np.array(['a', 'b']), obj=0, values=(2, 3)) # equivale a mesma coisa para a indexaçao de lista

array(['2', '3', 'a', 'b'], dtype='<U1')

In [45]:
array = np.array(lista_da_tupla).reshape(2, 3) # reshape é para mudar a forma do array, nesse caso, para 2 linhas e 3 colunas
array.shape

(2, 3)

In [48]:
df = pd.DataFrame(array)   
df

,0,1,2
0,1,2,5
1,1,2,20


In [49]:
df += df
df

,0,1,2
0,2,4,10
1,2,4,40


In [52]:
array_ones = np.ones_like(df)
array_ones[1,1] = 100
array_ones

array([[  1,   1,   1],
       [  1, 100,   1]])

In [53]:
df += array_ones
df

,0,1,2
0,4,6,12
1,4,204,42


# Operadores Relacionais


In [54]:
"Py" != "Py"

False

In [55]:
type(1) == type(3)

True

In [56]:
'1'== True

False

In [57]:
1.0 == True

True

In [59]:
2 >= 2.01

False

In [60]:
2 <= 3 < 4

True

In [61]:
(1, 2) == (1.0, 2.0)

True

In [63]:
lista_1 = [1, 2, 3]
lista_2 = (1, 2, 3)

In [64]:
lista_1 == lista_2

False

In [86]:
np.random.seed(42) # para garantir que os números gerados sejam os mesmos toda vez que o código for rodado
array_np = np.random.normal(0, 1, 1000).reshape(-1, 10) #0 é a média, 1 é o desvio padrão e 10 é o número de elementos que eu quero gerar
array_np_2 = np.random.normal(0, 1, 1000).reshape(-1, 10)
print(array_np[:1])
print(array_np_2[:1])

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473 -0.46947439  0.54256004]]
[[ 1.39935544  0.92463368  0.05963037 -0.64693678  0.69822331  0.39348539
   0.89519322  0.6351718   1.04955272 -0.53523521]]


In [87]:
array_np == array_np_2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

In [88]:
pd.DataFrame(array_np) <= pd.DataFrame(array_np_2)

,0,1,2,3,4,5,6,7,8,9
0,True,True,False,False,True,True,False,False,True,False
1,True,True,True,True,True,True,True,False,True,True
2,False,False,False,True,True,True,True,False,True,False
3,True,False,True,True,False,True,False,True,True,True
4,True,False,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...
95,False,True,True,False,False,True,False,True,True,False
96,False,False,True,False,True,False,True,False,False,True
97,True,False,False,True,True,True,True,True,True,False
98,False,False,True,True,True,True,False,False,False,True


In [90]:
df_1 = pd.DataFrame(array_np)
df_2 = pd.DataFrame(array_np_2)
df_1.head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040
